[viewer]
    Title = "Go语言博客"
    Description = "Go语言博客"
    Logo = "/resource/images/logo.png"
    Navigation = ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
    Bilibili = "https://space.bilibili.com/473844125"
    Zhihu = "https://www.zhihu.com/people/ma-shen-zhi-lu"
    Avatar = "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Finews.gtimg.com%2Fnewsapp_bt%2F0%2F13147603927%2F1000.jpg&refer=http%3A%2F%2Finews.gtimg.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1647242040&t=c6108010ed46b4acebe18955acdd2d24"
    UserName = "张三"
    UserDesc = "长得非常帅的程序员"
[system]
    CdnURL = "https://static.mszlu.com/goblog/es6/md-assets"
    QiniuAccessKey = "1d23au4qtM_B6cIOmhNBw9ZH_GI43oOvy8yoQw7B"
    QiniuSecretKey = "IgFT903uhqB_bKZCxogZZwGS0nFGE13JgD4BCudS"
    Valine = true
    ValineAppid = "FYj1jqdv5tqvueYqciZ7Qr7Y-gzGzoHsz"
    ValineAppkey = "HP3j7PixDXrffVE5bULfnPJ4"
    ValineServerURL = "https://fyj1jqdv.lc-cn-n1-shared.com"